import { OutletContext, PagesLayoutProps } from './app.types';
import {
  GameState,
  GameMode,
  TimePerQuestion,
  QuestionCount,
  SingleNumberConfig,
  TwoNumbersConfig,
  GameConfig,
  Question,
  GameResult,
  GameSliceState,
  SettingValue,
  SettingsOption,
  TimePerQuestionOption,
  QuestionCountOption,
} from './game.types';
export type {
  OutletContext,
  PagesLayoutProps,
  GameState,
  GameMode,
  TimePerQuestion,
  QuestionCount,
  SingleNumberConfig,
  TwoNumbersConfig,
  GameConfig,
  Question,
  GameResult,
  GameSliceState,
  SettingValue,
  SettingsOption,
  TimePerQuestionOption,
  QuestionCountOption,
};
